// <auto-generated>
using System.Reflection;


namespace System
{
    internal static partial class SR
    {
        internal static string InvalidLowBoundArgumentEx => "Value of '{1}' is not valid for '{0}'. '{0}' must be greater than or equal to {2}.";

        internal static string InvalidBoundArgument => "Value of '{1}' is not valid for '{0}'. '{0}' should be between {2} and {3}.";

        internal static string InvalidArgument => "InvalidArgument=Value of '{1}' is not valid for '{0}'.";

        internal static string HelpInvalidURL  => "Help URL '{0}' is not valid.";
    }
}
